index:
    path: /
    controller: App\Controller\DefaultController::index

film:
    path: /film/{id}
    controller: App\Controller\FilmController::showFilm

login:
    path: /login
    controller: App\Controller\UserController::login

category:
    path: /category/{id}
    controller: App\Controller\CategoryController::listFilmsFromCategory

user:
    path: /user/{id}
    controller: App\Controller\UserController::showUserDetails