index:
    path: /
    controller: App\Controller\DefaultController::index

film:
    path: /film/{id}
    controller: App\Controller\FilmController::showFilm

login:
    path: /login
    controller: App\Controller\UserController::login

category:
    path: /category/{id}
    controller: App\Controller\CategoryController::showFilms

user:
    path: /user/{id}
    controller: App\Controller\UserController::profile

newCategory:
    path: /new/category
    controller: App\Controller\CategoryController::addCategory

categories:
    path: /category
    controller: App\Controller\CategoryController::showCategories

categoryFilter:
    path: /category/filter/{letter}
    controller: App\Controller\CategoryController::filter

newUser:
    path: /new/user
    controller: App\Controller\UserController::addUser

newComment:
    path: /new/comment
    controller: App\Controller\CommentController::addComment

logout:
    path: /logout
